## travis setting
language: node_js
node_js:
  - "7"

stages:
  - Codecheck
  - Coverage

branches:
  only:
  - develop
  - master

stages:
  - name: Codecheck
    if: branch = develop OR branch = master OR type IN (pull_request)
  - name: build
    if: branch = develop OR branch = master OR type IN (pull_request)

jobs:
  include:
    - stage: Codecheck
      env: DESC=es-lint
      script: yarn run lint
    - stage: Codecheck
      env: DESC=style-lint
      script: yarn run stylelint
    - stage: build
      script: yarn run build
